<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$route['default_controller']                        = 'auth/admin_login/login';
$route['Status/Drawing']                            = "reports/drawing";
$route['Status/Delivery']                           = "reports/delivery";
$route['Status/Production']                         = "reports/production";
$route['Delivery']                                  = "projects/PlanDelivery";
$route['Production']                                = "projects/PlanProduction";
$route['Drawing']                                   = "projects/ProjectPanel";
$route['Control']                                   = "projects";
$route['Stuff']                                     = "employee";
$route['StuffControl']                              = "employee/employeePanel";
$route['Home']                                      = "home";
$route['News']                                      = "home/news";
$route['LatestWork']                                = "home/LatestWork";
$route['Gallery']                                   = "home/Gallery";
$route['Client']                                    = "home/Client";
$route['Dashboard']                                 = "dashboard";
$route['Service']                                   = "service";
$route['Carrer']                                    = "carrer";
$route['Applicant']                                 = "carrer/applicant";
$route['Instructor']                                = "training/instructor";
$route['Student']                                   = "training/student";
$route['Course']                                    = "training/course";
$route['Batch']                                     = "training/batch";
$route['Instructor/save/(:any)']                    = "training/save/$1";
$route['Student/save/(:any)']                       = "training/save/$1";
$route['Course/save/(:any)']                        = "training/save/$1";
$route['Batch/save/(:any)']                         = "training/save/$1";
$route['Instructor/Action/(:any)/(:any)/(:any)']    = "training/action/$1/$2/$3";
$route['Student/Action/(:any)/(:any)/(:any)']       = "training/action/$1/$2/$3";
$route['Course/Action/(:any)/(:any)/(:any)']        = "training/action/$1/$2/$3";
$route['Batch/Action/(:any)/(:any)/(:any)']         = "training/action/$1/$2/$3";
$route['Download/(:any)']                           = 'carrer/download/$1';
$route['404_override']                              = '';
$route['translate_uri_dashes']                      = FALSE;
